# -*- coding: utf-8 -*-
"""language_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2tXw22umXasCH3xdiofYEXwAKSixJqO
"""

completed                = True         # Change this flag to True when you've completed the assignment.
expected_completion_date = '03/08/2025'  # If your assignment is late, change this date to your expected completion date.
questions_or_comments    = ""            # Fill in this string with any questions or comments you have; leave empty if none.
extensions               = True         # Change this flag to True if you completed the extension for this assignment.
extensions_description   = ""            # If you did any extension, briefly explain what you did and where we should look for it.

"""
GramModels: Train and evaluate n-gram language models with add-k smoothing.

This module provides a class NgramLanguageModel to train unigram and bigram
language models on a text corpus, and evaluate their perplexity. It uses
add-k smoothing to handle unseen words.

Key features:
- Trains on a line-delimited text file
- Stores unigram and bigram counts, and pre-computes log probabilities
- Handles unknown words with add-k smoothing
- Calculates perplexity on train and test sets
- Tracks training and testing time
"""

import math
from collections import defaultdict


class NgramLanguageModel:
    """
    Class to train and run n-gram language models with add-k smoothing.
    """

    def __init__(self):
        """Initialize model hyperparameters and data structures."""
        self.unigram_counts = defaultdict(int)  # Dictionary to store unigram counts
        self.bigram_counts = defaultdict(int)   # Dictionary to store bigram counts
        self.k = 0.01                           # Smoothing parameter
        self.train_token_count = 0              # Total tokens in training data
        self.unigram_log_prob = {}              # Dictionary to store unigram log probabilities
        self.bigram_log_prob = {}               # Dictionary to store bigram log probabilities

    def train(self, infile='samiam.train'):
        """
        Train the n-gram model on the given text file.

        Reads the text line by line, splitting into tokens. Counts unigrams
        and bigrams, then pre-computes log probabilities with add-k smoothing.
        """
        with open(infile) as f:
          for line in f:
            # Add sentence boundary tokens
            tokens = ['<s>'] + line.split() + ['</s>']
            self.train_token_count += len(tokens)   # Update total token count

            # Count unigrams
            for token in tokens:
              self.unigram_counts[token] += 1       # Increment unigram count

            # Count bigrams
            for bigram in zip(tokens, tokens[1:]):
              bigram_key = f"{bigram[0]}_{bigram[1]}"
              self.bigram_counts[bigram_key] += 1   # Increment bigram count

          vocab_size = len(self.unigram_counts)    # Total unique words

          # Pre-compute smoothed unigram log probabilities
          for token, count in self.unigram_counts.items():
            prob = (count + self.k) / (self.train_token_count + self.k * vocab_size)  # Smoothed probability
            self.unigram_log_prob[token] = math.log(prob)   # Store log probability

          # Pre-compute smoothed bigram log probabilities
          for bigram, count in self.bigram_counts.items():
            context = bigram.split('_')[0]         # Get context word
            unigram_count = self.unigram_counts[context]
            prob = (count + self.k) / (unigram_count + self.k * vocab_size)  # Smoothed probability
            self.bigram_log_prob[bigram] = math.log(prob)   # Store log probability

          # Compute log prob for unknown tokens
          unk_prob = self.k / (self.train_token_count + self.k * vocab_size)
          self.unigram_log_prob['&lt;unk&gt;'] = math.log(unk_prob)  # Store unknown unigram log prob
          self.bigram_log_prob['&lt;unk&gt;'] = math.log(unk_prob)   # Store unknown bigram log prob

    def predict_unigram(self, sentence):
        """Calculate unigram log probability of the given sentence."""
        log_prob = 0.0
        tokens = sentence.split() + ['</s>']   # Split sentence into tokens, add end token

        for token in tokens:
          # Retrieve log prob if token is known, else use unknown token prob
          log_prob += self.unigram_log_prob.get(token, self.unigram_log_prob['&lt;unk&gt;'])

        return log_prob

    def predict_bigram(self, sentence):
        """Calculate bigram log probability of the given sentence."""
        log_prob = 0.0
        tokens = ['<s>'] + sentence.split() + ['</s>']  # Add start and end tokens

        for bigram in zip(tokens, tokens[1:]):
          bigram_key = f"{bigram[0]}_{bigram[1]}"
          log_prob += self.bigram_log_prob.get(bigram_key, self.bigram_log_prob['&lt;unk&gt;'])

        return log_prob

    def test_perplexity(self, test_file, ngram_size='unigram'):
        """
        Compute perplexity of the model on the given test file.

        Reads the test data line by line and calculates log probability
        of each sentence using the trained unigram or bigram model. Computes
        perplexity as exp(-average_log_prob) over the whole test set.
        """
        total_log_prob = 0.0
        total_tokens = 0

        with open(test_file) as f:
          for line in f:
            sentence = line.strip()
            if ngram_size == 'unigram':
              total_log_prob += self.predict_unigram(sentence)   # Add unigram log prob
            else:
              total_log_prob += self.predict_bigram(sentence)    # Add bigram log prob

            total_tokens += len(sentence.split()) + 1           # Update total test tokens

        avg_log_prob = total_log_prob / total_tokens   # Compute average log prob
        perplexity = math.exp(-avg_log_prob)            # Perplexity = exp(-avg_log_prob)

        return perplexity


if __name__ == '__main__':
    """Main section to train model and evaluate on train/test sets."""
    import time

    ngram_lm = NgramLanguageModel()

    start = time.time()

    # Train model and report training time
    ngram_lm.train('samiam.train')

    # Compute train and test perplexity for unigram and bigram models
    train_unigram_perp = ngram_lm.test_perplexity('samiam.train')
    train_bigram_perp = ngram_lm.test_perplexity('samiam.train', 'bigram')
    test_unigram_perp = ngram_lm.test_perplexity('samiam.test')
    test_bigram_perp = ngram_lm.test_perplexity('samiam.test', 'bigram')

    print('Training time:\t', time.time() - start)
    print('Training perplexity, unigram:\t', ngram_lm.test_perplexity('samiam.train'))
    print('Training perplexity, bigram:\t', ngram_lm.test_perplexity('samiam.train', 'bigram'))
    print('Test perplexity, unigram:\t', ngram_lm.test_perplexity('samiam.test'))
    print('Test perplexity, bigram:\t', ngram_lm.test_perplexity('samiam.test', 'bigram'))