# -*- coding: utf-8 -*-
"""BioBERTv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsSMDVc_D5W91-58OgouaNT1Z2HVTKle
"""

!pip install kaggle
!kaggle datasets download -d sananmuzaffarov/european-football-injuries-2020-2025
!unzip european-football-injuries-2020-2025.zip

import pandas as pd
import numpy as np

df = pd.read_csv('full_dataset_thesis - 1.csv')

# Basic Labeling/Exploring
print(f"Total Records: {len(df)}")
print(f"Total Columns: {len(df.columns)}")
print(f"\nColumns: {df.columns.tolist()}")

#print(df.head())
# Check for the injurt description column
print(f"\nSample injury types: ")
print(df['Injury'].head(20))

# Convert dates to datetime
df['injury_start'] = pd.to_datetime(df['injury_from_parsed'])
df['injury_end'] = pd.to_datetime(df['injury_until_parsed'])

# Calculate duration
df['days_missed'] = (df['injury_end'] - df['injury_start']).dt.days

# Remove invalid entries
df = df[df['days_missed'] >= 0] # negative days = error

# Output Data Stats
print(f"\nDays Missed statistics: ")
print(df['days_missed'].describe())

from __future__ import print_function
def classify_severity(days):
  """
  Classify injury severity by days missed
  """
  if days < 7:
    return 'Minor'
  elif days < 21:
    return 'Short-Term'
  elif days < 60:
    return 'Medium-Term'
  elif days < 180:
    return 'Long-Term'
  else:
    return 'Season-Ending'

# Apply Classification
df['severity'] = df['days_missed'].apply(classify_severity)

# Convert to numeric labels for model
severity_mapping = {
    'Minor': 0,
    'Short-Term': 1,
    'Medium-Term': 2,
    'Long-Term': 3,
    'Season-Ending': 4
}
df['severity_'] = df['severity'].map(severity_mapping)

# Check class distribution
print("\nSeverity Distribution:")
print(df['severity'].value_counts())
print("\nClass percentages: ")
print(df['severity'].value_counts(normalize=True) * 100) # Class % Distribution represented w/ decimal

# Assuming the injury column is named 'Injury'
# Adjust based on actual column name in your dataset

# Remove missing values
df = df[df['Injury'].notna()]

# Clean text (optional - BioBERT handles most cases well)
df['injury_text'] = df['Injury'].str.strip()

# Remove any extremely short descriptions (likely errors)
df = df[df['injury_text'].str.len() > 2]

print(f"\nFinal dataset size: {len(df)} records")
print(f"\nSample injury texts:")
for i, text in enumerate(df['injury_text'].head(10)):
    print(f"{i+1}. {text}")

# 1. Reload the data (or use a backup if you made one earlier)
df_full = pd.read_csv('full_dataset_thesis - 1.csv')

# 2. Identify the short ones BEFORE you filter the main dataframe
short_records = df_full[df_full['Injury'].fillna('').str.len() <= 2]
missing_records = df_full[df_full['Injury'].isna()]

# 3. Print them out to inspect
print("--- SHORT DESCRIPTIONS (0-3 chars) ---")
print(short_records['Injury'].unique())

print("\n--- SAMPLE OF DATA THAT WOULD BE REMOVED ---")
print(short_records[['Injury', 'player_name']].head(10))

# Seperate Datast
# TRAIN / TEST / VALIDATION
# 80/10/10
from sklearn.model_selection import train_test_split

# Create feature and label arrays
X = df['injury_text'].values # Text input
y = df['severity_'].values # Numeric labels (0-4)

# First split: 80% train, 20% temp (10%val + 10%test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.2,      # 20% for val+test
    random_state=42,
    stratify=y    # Maintain class distribution
)

# Second split:
X_val, X_test, y_val, y_test = train_test_split(
     X_temp, y_temp,
    test_size=0.5,      # 50% of 20% for 10% of total
    random_state=42,
    stratify=y_temp     # Maintain class distribution
)


# Verify total percentages
total_samples = len(X)
print(f"Total Samples: {total_samples}")
print(f"Train Samples: {len(X_train)} samples ({len(X_train)/total_samples*100:.1f}%)")
print(f"Validation Samples: {len(X_val)} samples ({len(X_val)/total_samples*100:.1f}%)")
print(f"Test Samples: {len(X_test)} samples ({len(X_test)/total_samples*100:.1f}%)")

# Check class distribution in each split
print("\n" + "-"*60)
print("CLASS DISTRIBUTION ACROSS SPLITS")
print("="*60)

severity_names = ['Minor', 'Short-Term', 'Medium-Term', 'Long-Term', 'Season-Ending']

for split_name, split_labels in [('Training ', y_train), ('Validation ', y_val), ('Test ', y_test)]:
    print(f"\n{split_name} set distribution:")
    unique, counts = np.unique(split_labels, return_counts=True)
    for label, count in zip(unique, counts):
        print(f"{severity_names[label]}: {count} samples ({count/len(split_labels)*100:5.1f}%)")

# TOKENIZE for BioBERT
from transformers import AutoTokenizer

# Load BioBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained('dmis-lab/biobert-v1.1')

# Tokenize all splits
train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    X_val.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

print("Tokenization complete!")
print(f"Example tokenized injury:")
print(f"Text: {X_train[0]}")
print(f"Token IDs: {train_encodings['input_ids'][0][:20]}...")  # First 20 tokens

# CREATE DATASET CLASS

import torch

class InjuryDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Create datasets
train_dataset = InjuryDataset(train_encodings, y_train)
val_dataset = InjuryDataset(val_encodings, y_val)
test_dataset = InjuryDataset(test_encodings, y_test)

# Load BioBERT Model

from transformers import AutoModelForSequenceClassification

# Load for classification
model = AutoModelForSequenceClassification.from_pretrained(
    'dmis-lab/biobert-v1.1',
    num_labels=5, # 5 severity classes
    problem_type="single_label_classification"
)

# Debug
print(f'Model loaded: {model.__class__.__name__}')
print(f'Number of parameters: {model.num_parameters()}')

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=32,     # Batch size
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="epoch",              # Evaluate on each epoch
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    save_total_limit=2                  # Keep best 2 checkpoints
)

# Evaluation Metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    # Calculate metrics (f1 score)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='weighted'
    )
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Train the Model
from transformers import Trainer

# Create trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# Start training
print("Start training...")
trainer.train()

print("\nTraining complete!")

# EVALUATE RESULTS
# Test Set Evaluation

test_results = trainer.evaluate(test_dataset)

print("\n" + "="*50)
print("TEST SET RESULTS")
print("="*50)
for metric, value in test_results.items():
    print(f"{metric}: {value:.4f}")

import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# Get predictions
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(-1)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=severity_names,
    yticklabels=severity_names
    )
plt.title('BioBERT Injurt Severity Classification - Confusion Matrix')
plt.xlabel('Predicted - Severity')
plt.ylabel('Actual - Severity')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300)
plt.show()

# Classification report
print("\n" + "="*50)
print("CLASSIFICATION REPORT")
print("="*50)
print(classification_report(y_test, y_pred, target_names=severity_names))

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.special import softmax
from sklearn.metrics import (
    roc_curve, auc, roc_auc_score,
    precision_recall_curve, average_precision_score,
    f1_score, confusion_matrix, classification_report,
)
from sklearn.preprocessing import label_binarize

# Pull predictions from the already-trained model
predictions = trainer.predict(test_dataset)
logits = predictions.predictions          # shape: (n_test, 5)
y_true = predictions.label_ids            # shape: (n_test,)
y_probs = softmax(logits, axis=-1)        # shape: (n_test, 5) — rows sum to 1
y_pred_default = logits.argmax(axis=-1)   # default argmax decision

n_classes = 5
class_names = ['Minor', 'Short-Term', 'Medium-Term', 'Long-Term', 'Season-Ending']

# Sanity checks
print(f"Logits shape: {logits.shape}")
print(f"Probabilities sum to ~1 per row: {np.allclose(y_probs.sum(axis=1), 1.0)}")
print(f"\nTest set class distribution:")
for i, name in enumerate(class_names):
    n = (y_true == i).sum()
    print(f"  {name:<15} n = {n:4d} ({n/len(y_true)*100:5.1f}%)")

auc_macro_ovr    = roc_auc_score(y_true, y_probs, multi_class='ovr', average='macro')
auc_weighted_ovr = roc_auc_score(y_true, y_probs, multi_class='ovr', average='weighted')
auc_micro_ovr    = roc_auc_score(
    label_binarize(y_true, classes=list(range(n_classes))).ravel(),
    y_probs.ravel()
)
auc_macro_ovo    = roc_auc_score(y_true, y_probs, multi_class='ovo', average='macro')
auc_weighted_ovo = roc_auc_score(y_true, y_probs, multi_class='ovo', average='weighted')

print("="*60)
print("MULTI-CLASS AUC SUMMARY")
print("="*60)
print(f"  Macro    OvR AUC : {auc_macro_ovr:.4f}")
print(f"  Weighted OvR AUC : {auc_weighted_ovr:.4f}")
print(f"  Micro    OvR AUC : {auc_micro_ovr:.4f}")
print(f"  Macro    OvO AUC : {auc_macro_ovo:.4f}")
print(f"  Weighted OvO AUC : {auc_weighted_ovo:.4f}")
print("="*60)
print("\nReference points:")
print("  0.50 = random guessing")
print("  0.70 = acceptable separability")
print("  0.80 = good separability")
print("  0.90 = excellent separability")

# Binarize for OvR
y_true_bin = label_binarize(y_true, classes=list(range(n_classes)))

# Per-class ROC
fpr, tpr, roc_auc_per_class = {}, {}, {}
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc_per_class[i] = auc(fpr[i], tpr[i])

# Plot
plt.figure(figsize=(9, 7))
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
for i, color in zip(range(n_classes), colors):
    n_pos = int(y_true_bin[:, i].sum())
    plt.plot(
        fpr[i], tpr[i], color=color, lw=2.2,
        label=f'{class_names[i]:<14} AUC = {roc_auc_per_class[i]:.3f}  (n={n_pos})'
    )

plt.plot([0, 1], [0, 1], 'k--', lw=1, alpha=0.5, label='Random (AUC = 0.500)')
plt.xlim([0.0, 1.0]); plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate', fontsize=11)
plt.ylabel('True Positive Rate (Recall)', fontsize=11)
plt.title(
    f'Per-Class ROC Curves (One-vs-Rest)\n'
    f'Macro AUC = {auc_macro_ovr:.3f}  |  Weighted AUC = {auc_weighted_ovr:.3f}',
    fontsize=12
)
plt.legend(loc='lower right', fontsize=10, framealpha=0.95)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('roc_curves_per_class.png', dpi=300, bbox_inches='tight')
plt.show()

# Tabular summary
print("\nPer-class AUC (sorted, lowest first — worst separability at top):")
ordered = sorted(range(n_classes), key=lambda i: roc_auc_per_class[i])
for i in ordered:
    print(f"  {class_names[i]:<15} AUC = {roc_auc_per_class[i]:.4f}")

plt.figure(figsize=(9, 7))
ap_per_class = {}
for i, color in zip(range(n_classes), colors):
    precision_i, recall_i, _ = precision_recall_curve(y_true_bin[:, i], y_probs[:, i])
    ap_i = average_precision_score(y_true_bin[:, i], y_probs[:, i])
    ap_per_class[i] = ap_i
    prevalence = y_true_bin[:, i].mean()
    plt.plot(
        recall_i, precision_i, color=color, lw=2.2,
        label=f'{class_names[i]:<14} AP = {ap_i:.3f}  (baseline = {prevalence:.3f})'
    )
    plt.axhline(y=prevalence, color=color, linestyle=':', alpha=0.4, lw=1)

plt.xlim([0.0, 1.0]); plt.ylim([0.0, 1.05])
plt.xlabel('Recall', fontsize=11)
plt.ylabel('Precision', fontsize=11)
plt.title('Per-Class Precision-Recall Curves\nDotted lines = class prevalence (random-classifier baseline)', fontsize=12)
plt.legend(loc='best', fontsize=10, framealpha=0.95)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('pr_curves_per_class.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nAP / prevalence ratio (how much better than random):")
for i in range(n_classes):
    prevalence = y_true_bin[:, i].mean()
    lift = ap_per_class[i] / prevalence if prevalence > 0 else float('nan')
    print(f"  {class_names[i]:<15} AP/prev = {lift:5.2f}x  (AP={ap_per_class[i]:.3f}, prev={prevalence:.3f})")

print("="*88)
print("THRESHOLD OPTIMIZATION (per class, one-vs-rest)")
print("="*88)
header = f"{'Class':<15}{'AUC':>7}{'Argmax F1':>12}{'Naive(0.20) F1':>16}{'Best Thresh':>14}{'Best F1':>10}{'Δ vs Argmax':>14}"
print(header)
print("-"*88)

optimal_thresholds = {}
for i in range(n_classes):
    # Argmax F1 (what the model actually does)
    argmax_pred = (y_pred_default == i).astype(int)
    argmax_f1 = f1_score(y_true_bin[:, i], argmax_pred, zero_division=0)

    # Naive 1/K threshold
    naive_pred = (y_probs[:, i] >= 1/n_classes).astype(int)
    naive_f1 = f1_score(y_true_bin[:, i], naive_pred, zero_division=0)

    # Sweep
    thresholds = np.linspace(0.01, 0.99, 99)
    f1_scores = [
        f1_score(y_true_bin[:, i], (y_probs[:, i] >= t).astype(int), zero_division=0)
        for t in thresholds
    ]
    best_idx = int(np.argmax(f1_scores))
    best_t = thresholds[best_idx]
    best_f1 = f1_scores[best_idx]
    optimal_thresholds[i] = best_t

    delta = best_f1 - argmax_f1
    delta_str = f"+{delta:.3f}" if delta >= 0 else f"{delta:.3f}"

    print(
        f"{class_names[i]:<15}{roc_auc_per_class[i]:>7.3f}{argmax_f1:>12.3f}"
        f"{naive_f1:>16.3f}{best_t:>14.3f}{best_f1:>10.3f}{delta_str:>14}"
    )
print("="*88)

plt.figure(figsize=(9, 6))
thresholds = np.linspace(0.01, 0.99, 99)
for i, color in zip(range(n_classes), colors):
    f1_scores = [
        f1_score(y_true_bin[:, i], (y_probs[:, i] >= t).astype(int), zero_division=0)
        for t in thresholds
    ]
    plt.plot(thresholds, f1_scores, color=color, lw=2,
             label=f'{class_names[i]} (best @ {optimal_thresholds[i]:.2f})')
    plt.axvline(optimal_thresholds[i], color=color, linestyle=':', alpha=0.4)

plt.axvline(1/n_classes, color='gray', linestyle='--', alpha=0.6, label=f'Naive 1/K = {1/n_classes:.2f}')
plt.xlabel('Decision threshold (OvR probability)', fontsize=11)
plt.ylabel('F1 score', fontsize=11)
plt.title('F1 vs. Threshold — per class', fontsize=12)
plt.legend(loc='best', fontsize=9)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('f1_vs_threshold.png', dpi=300, bbox_inches='tight')
plt.show()

thresh_vec = np.array([optimal_thresholds[i] for i in range(n_classes)])
scaled_probs = y_probs / thresh_vec  # broadcast over class axis
y_pred_tuned = scaled_probs.argmax(axis=-1)

cm_default = confusion_matrix(y_true, y_pred_default)
cm_tuned   = confusion_matrix(y_true, y_pred_tuned)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
for ax, cm, title in zip(
    axes,
    [cm_default, cm_tuned],
    ['Default (argmax)', 'Tuned (threshold-scaled argmax)']
):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names, ax=ax, cbar=False)
    ax.set_title(f'{title}', fontsize=12)
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')
plt.suptitle('Confusion Matrix — before vs. after threshold tuning', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('confusion_matrix_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n--- DEFAULT (argmax) ---")
print(classification_report(y_true, y_pred_default, target_names=class_names, zero_division=0))
print("\n--- TUNED (threshold-scaled argmax) ---")
print(classification_report(y_true, y_pred_tuned, target_names=class_names, zero_division=0))

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score
from scipy.special import softmax

def compute_metrics(pred):
    """
    Custom metrics for HF Trainer.
    Adds macro/weighted one-vs-rest AUC on top of accuracy/precision/recall/F1.
    AUC is computed from softmaxed logits — threshold-independent.
    """
    labels = pred.label_ids
    logits = pred.predictions
    preds = logits.argmax(axis=-1)
    probs = softmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='weighted', zero_division=0
    )
    acc = accuracy_score(labels, preds)

    # AUC requires every class to appear in `labels`. In tiny eval splits a class
    # can be missing — guard against that to avoid crashing the training loop.
    try:
        auc_macro = roc_auc_score(labels, probs, multi_class='ovr', average='macro')
        auc_weighted = roc_auc_score(labels, probs, multi_class='ovr', average='weighted')
    except ValueError:
        auc_macro = float('nan')
        auc_weighted = float('nan')

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'auc_macro': auc_macro,
        'auc_weighted': auc_weighted,
    }

print("Updated compute_metrics defined.")
print("To use it: re-run training with this function passed into Trainer.")
print("To select best checkpoint by AUC: set metric_for_best_model='auc_macro' in TrainingArguments.")

# ERROR ANALYSIS

# Find misclassified examples
errors = []
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    if true != pred:
        errors.append({
            'text': X_test[i],
            'true_label': list(severity_mapping.keys())[true],
            'predicted_label': list(severity_mapping.keys())[pred],
            'days_missed': df.iloc[i]['days_missed']
        })
# Show 10 worst errors
print("\n" + "="*50)
print("SAMPLE MISCLASSIFICATIONS")
print("="*50)
for idx, error_data in enumerate(errors[:10]):
    print(f"\n{idx+1}. Injury: {error_data['text']}")
    print(f"   True: {error_data['true_label']} | Predicted: {error_data['predicted_label']}")

# Save the fine-tuned model
model.save_pretrained('./biobert_injury_classifier')
tokenizer.save_pretrained('./biobert_injury_classifier')

print("Model saved to './biobert_injury_classifier'")

# Save results to CSV
results_df = pd.DataFrame({
    'injury_text': X_test,
    'true_label': [list(severity_mapping.keys())[i] for i in y_test],
    'predicted_label': [list(severity_mapping.keys())[i] for i in y_pred]
})
results_df.to_csv('injury_classification_results.csv', index=False)

print("Results saved to 'injury_classification_results.csv'")

# TEST ON NEW INJURIES

def predict_severity(injury_text):
  """
  Predict severity for a new injury description
  """
  # Tokenize
  inputs = tokenizer(
      injury_text,
      return_tensors='pt',
      truncation=True,
      padding=True,
      max_length=128,
  )

  # Get the device of the model
  device = model.parameters().__next__().device

  # Move input tensors to the same device as the model
  inputs = {key: val.to(device) for key, val in inputs.items()}

  # Predict
  model.eval()
  with torch.no_grad():
    outputs = model(**inputs)
    prediction = outputs.logits.argmax(-1).item()

  # Get severity name
  severity_name = list(severity_mapping.keys())[prediction]

  # Get confidence scores
  probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
  # Move probabilities back to CPU for easier printing/handling if needed
  probabilities = probabilities.cpu()

  return severity_name, probabilities

# Test examples
test_injuries = [
    "Hamstring Strain",
    "Anterior Ligament Rupture",
    "Minor Ankle Knock",
    "Fractured Metatarsal"
]

print("\n" + "="*50)
print("PREDICTIONS ON NEW INJURIES")
print("="*50)

for injury in test_injuries:
  severity, confidences = predict_severity(injury)
  print(f"\nInjury: {injury}")
  print(f"Predicted Severity: {severity}")
  print(f"Confidence Scores:")
  for name, prob in zip(severity_names, confidences):
    print(f"{name}: {prob:.2%}")

# ============================================================================
# SUPPLEMENTARY VISUALIZATIONS FROM BioBERTv2
# ============================================================================
# This script adds the graphs from v2 that weren't in the complete analysis
# Run this AFTER running biobert_complete_analysis.py
# ============================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    f1_score,
    roc_auc_score
)
from sklearn.preprocessing import label_binarize

print("="*80)
print("SUPPLEMENTARY VISUALIZATIONS FROM v2")
print("="*80)

severity_names = ['Minor', 'Short-Term', 'Medium-Term', 'Long-Term', 'Season-Ending']
n_classes = 5
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

# ============================================================================
# SETUP: Get predictions and probabilities
# ============================================================================

# Get probabilities
import torch
y_probs = predictions.predictions
y_probs_softmax = torch.nn.functional.softmax(torch.tensor(y_probs), dim=-1).numpy()

y_true = y_test
y_pred_default = y_pred

# Binarize labels for some calculations
y_true_bin = label_binarize(y_true, classes=list(range(n_classes)))

# ============================================================================
# ADDITIONAL AUC METRICS (OvO and Micro)
# ============================================================================

print("\n1. CALCULATING ADDITIONAL AUC METRICS")
print("-"*80)

# We already have Macro and Weighted from the main script
# Add Micro and One-vs-One (OvO)

auc_macro_ovr = roc_auc_score(y_true, y_probs_softmax, multi_class='ovr', average='macro')
auc_weighted_ovr = roc_auc_score(y_true, y_probs_softmax, multi_class='ovr', average='weighted')
auc_micro_ovr = roc_auc_score(
    label_binarize(y_true, classes=list(range(n_classes))).ravel(),
    y_probs_softmax.ravel()
)
auc_macro_ovo = roc_auc_score(y_true, y_probs_softmax, multi_class='ovo', average='macro')
auc_weighted_ovo = roc_auc_score(y_true, y_probs_softmax, multi_class='ovo', average='weighted')

print("="*60)
print("MULTI-CLASS AUC SUMMARY")
print("="*60)
print(f"  Macro    OvR AUC : {auc_macro_ovr:.4f}")
print(f"  Weighted OvR AUC : {auc_weighted_ovr:.4f}")
print(f"  Micro    OvR AUC : {auc_micro_ovr:.4f}")
print(f"  Macro    OvO AUC : {auc_macro_ovo:.4f}")
print(f"  Weighted OvO AUC : {auc_weighted_ovo:.4f}")
print("="*60)
print("\nReference points:")
print("  0.50 = random guessing")
print("  0.70 = acceptable separability")
print("  0.80 = good separability")
print("  0.90 = excellent separability")

# ============================================================================
# GRAPH 9: F1 vs THRESHOLD (THRESHOLD TUNING ANALYSIS)
# ============================================================================

print("\n\n2. GENERATING THRESHOLD TUNING VISUALIZATIONS")
print("-"*80)
print("Creating Graph 9: F1 vs Threshold...")

# Find optimal threshold for each class
thresholds = np.linspace(0.01, 0.99, 99)
optimal_thresholds = []

for i in range(n_classes):
    f1_scores = [
        f1_score(y_true_bin[:, i], (y_probs_softmax[:, i] >= t).astype(int), zero_division=0)
        for t in thresholds
    ]
    optimal_idx = np.argmax(f1_scores)
    optimal_thresholds.append(thresholds[optimal_idx])

optimal_thresholds = np.array(optimal_thresholds)

# Plot F1 vs Threshold for each class
plt.figure(figsize=(10, 7))

for i, color in zip(range(n_classes), colors):
    f1_scores = [
        f1_score(y_true_bin[:, i], (y_probs_softmax[:, i] >= t).astype(int), zero_division=0)
        for t in thresholds
    ]

    # Highlight Season-Ending with thicker line
    if i == 4:  # Season-Ending
        plt.plot(thresholds, f1_scores, color=color, lw=3, linestyle='--',
                label=f'{severity_names[i]} (best @ {optimal_thresholds[i]:.2f}) ★')
    else:
        plt.plot(thresholds, f1_scores, color=color, lw=2,
                label=f'{severity_names[i]} (best @ {optimal_thresholds[i]:.2f})')

    # Mark optimal threshold
    plt.axvline(optimal_thresholds[i], color=color, linestyle=':', alpha=0.4, linewidth=1.5)

# Add reference line
plt.axvline(1/n_classes, color='gray', linestyle='--', alpha=0.6,
           label=f'Naive 1/K = {1/n_classes:.2f}')

plt.xlabel('Decision Threshold (Probability)', fontweight='bold', fontsize=12)
plt.ylabel('F1-Score', fontweight='bold', fontsize=12)
plt.title('F1-Score vs. Threshold by Class\n(Shows threshold optimization potential)',
         fontweight='bold', fontsize=13, pad=15)
plt.legend(loc='best', fontsize=10)
plt.grid(True, alpha=0.3, linestyle='--')
plt.xlim([0, 1])
plt.ylim([0, 1])

# Add annotation
plt.text(0.7, 0.2,
        'Season-Ending shows\nlarge threshold effect:\nF1 doubles from default',
        fontsize=10,
        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.6))

plt.tight_layout()
plt.savefig('graph9_f1_vs_threshold.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph9_f1_vs_threshold.png")

# Print optimal thresholds
print("\nOptimal Thresholds per Class:")
for i, name in enumerate(severity_names):
    print(f"  {name:15s}: {optimal_thresholds[i]:.3f}")

# ============================================================================
# GRAPH 10: CONFUSION MATRIX COMPARISON (DEFAULT vs TUNED)
# ============================================================================

print("\nCreating Graph 10: Confusion Matrix Comparison (Default vs Tuned)...")

# Apply threshold tuning
thresh_vec = np.array([optimal_thresholds[i] for i in range(n_classes)])
scaled_probs = y_probs_softmax / thresh_vec  # Scale probabilities by optimal thresholds
y_pred_tuned = scaled_probs.argmax(axis=-1)

# Create confusion matrices
cm_default = confusion_matrix(y_true, y_pred_default)
cm_tuned = confusion_matrix(y_true, y_pred_tuned)

# Plot side-by-side comparison
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

for ax, cm, title in zip(
    axes,
    [cm_default, cm_tuned],
    ['Default Model (argmax)', 'Threshold-Tuned Model']
):
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=severity_names, yticklabels=severity_names,
                ax=ax, cbar_kws={'label': 'Count'},
                linewidths=0.5, linecolor='gray')
    ax.set_title(title, fontweight='bold', fontsize=13, pad=10)
    ax.set_xlabel('Predicted Severity', fontweight='bold', fontsize=11)
    ax.set_ylabel('True Severity', fontweight='bold', fontsize=11)

plt.suptitle('Confusion Matrix: Before vs. After Threshold Tuning\n(Optimized thresholds improve Season-Ending recall)',
            fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('graph10_confusion_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph10_confusion_comparison.png")

# ============================================================================
# PERFORMANCE COMPARISON: DEFAULT vs TUNED
# ============================================================================

print("\n\n3. COMPARING DEFAULT vs TUNED PERFORMANCE")
print("-"*80)

print("\n--- DEFAULT MODEL (argmax) ---")
report_default = classification_report(y_true, y_pred_default,
                                       target_names=severity_names,
                                       output_dict=True,
                                       zero_division=0)
print(classification_report(y_true, y_pred_default,
                           target_names=severity_names,
                           zero_division=0))

print("\n--- TUNED MODEL (threshold-optimized) ---")
report_tuned = classification_report(y_true, y_pred_tuned,
                                    target_names=severity_names,
                                    output_dict=True,
                                    zero_division=0)
print(classification_report(y_true, y_pred_tuned,
                           target_names=severity_names,
                           zero_division=0))

# ============================================================================
# GRAPH 11: TUNING IMPACT BY CLASS
# ============================================================================

print("\nCreating Graph 11: Impact of Threshold Tuning by Class...")

# Extract F1 scores
f1_default = [report_default[name]['f1-score'] for name in severity_names]
f1_tuned = [report_tuned[name]['f1-score'] for name in severity_names]

# Calculate improvement
f1_improvement = [(tuned - default) for default, tuned in zip(f1_default, f1_tuned)]
f1_improvement_pct = [(tuned - default) / default * 100 if default > 0 else 0
                      for default, tuned in zip(f1_default, f1_tuned)]

# Create comparison plot
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: F1 comparison
x_pos = np.arange(len(severity_names))
width = 0.35

bars1 = axes[0].bar(x_pos - width/2, f1_default, width,
                    label='Default', color='steelblue', alpha=0.8, edgecolor='black')
bars2 = axes[0].bar(x_pos + width/2, f1_tuned, width,
                    label='Tuned', color='coral', alpha=0.8, edgecolor='black')

# Add value labels
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        axes[0].text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.3f}',
                    ha='center', va='bottom', fontsize=9)

axes[0].set_ylabel('F1-Score', fontweight='bold', fontsize=11)
axes[0].set_title('F1-Score: Default vs. Tuned', fontweight='bold', fontsize=12, pad=10)
axes[0].set_xticks(x_pos)
axes[0].set_xticklabels(severity_names, rotation=45, ha='right')
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3, linestyle='--')
axes[0].set_ylim([0, 1])

# Right: Improvement percentage
colors_improvement = ['green' if x > 0 else 'red' for x in f1_improvement_pct]
bars3 = axes[1].barh(severity_names, f1_improvement_pct, color=colors_improvement,
                     alpha=0.7, edgecolor='black')

# Add value labels
for i, (bar, pct) in enumerate(zip(bars3, f1_improvement_pct)):
    width = bar.get_width()
    label_x_pos = width + 2 if width > 0 else width - 2
    ha = 'left' if width > 0 else 'right'
    axes[1].text(label_x_pos, bar.get_y() + bar.get_height()/2,
                f'{pct:+.1f}%',
                ha=ha, va='center', fontweight='bold', fontsize=10)

axes[1].set_xlabel('F1-Score Improvement (%)', fontweight='bold', fontsize=11)
axes[1].set_title('Impact of Threshold Tuning', fontweight='bold', fontsize=12, pad=10)
axes[1].axvline(0, color='black', linewidth=1)
axes[1].grid(axis='x', alpha=0.3, linestyle='--')

# Add annotation
axes[1].text(0.5, 3.7,
            'Season-Ending:\nThreshold Issue',
            transform=axes[1].transData,
            fontsize=9,
            bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.7))

axes[1].text(0.5, 1.3,
            'Short/Medium:\nRepresentation\nProblem',
            transform=axes[1].transData,
            fontsize=9,
            bbox=dict(boxstyle='round', facecolor='lightcoral', alpha=0.7))

plt.tight_layout()
plt.savefig('graph11_tuning_impact.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph11_tuning_impact.png")

# ============================================================================
# SUMMARY TABLE: THRESHOLD TUNING RESULTS
# ============================================================================

print("\n\n4. GENERATING TUNING SUMMARY TABLE")
print("-"*80)

tuning_summary = pd.DataFrame({
    'Class': severity_names,
    'Optimal_Threshold': optimal_thresholds,
    'F1_Default': f1_default,
    'F1_Tuned': f1_tuned,
    'F1_Improvement': f1_improvement,
    'F1_Improvement_Pct': f1_improvement_pct
})

print("\nThreshold Tuning Impact Summary:")
print(tuning_summary.to_string(index=False))

tuning_summary.to_csv('biobert_threshold_tuning_summary.csv', index=False)
print("\n✓ Saved: biobert_threshold_tuning_summary.csv")

# Overall metrics comparison
print("\n\nOverall Performance Comparison:")
print(f"  Default Accuracy:  {report_default['accuracy']:.4f}")
print(f"  Tuned Accuracy:    {report_tuned['accuracy']:.4f}")
print(f"  Accuracy Change:   {report_tuned['accuracy'] - report_default['accuracy']:+.4f}")
print(f"\n  Default Macro F1:  {report_default['macro avg']['f1-score']:.4f}")
print(f"  Tuned Macro F1:    {report_tuned['macro avg']['f1-score']:.4f}")
print(f"  Macro F1 Change:   {report_tuned['macro avg']['f1-score'] - report_default['macro avg']['f1-score']:+.4f}")

# ============================================================================
# FINAL SUMMARY
# ============================================================================

print("\n\n" + "="*80)
print("SUPPLEMENTARY ANALYSIS COMPLETE")
print("="*80)

print("\n📊 Additional Visualizations Generated:")
print("  9.  graph9_f1_vs_threshold.png")
print("  10. graph10_confusion_comparison.png")
print("  11. graph11_tuning_impact.png")

print("\n📈 Additional Data Files:")
print("  3. biobert_threshold_tuning_summary.csv")

print("\n✅ Combined with main analysis, you now have 11 publication-ready graphs!")

print("\n" + "="*80)
print("KEY THRESHOLD TUNING FINDINGS:")
print("="*80)
print(f"1. Season-Ending optimal threshold: {optimal_thresholds[4]:.3f} (vs default 0.20)")
print(f"2. Season-Ending F1 improvement: {f1_improvement_pct[4]:+.1f}% ({f1_default[4]:.3f} → {f1_tuned[4]:.3f})")
print(f"3. Short-Term shows minimal improvement: {f1_improvement_pct[1]:+.1f}%")
print(f"4. Medium-Term shows minimal improvement: {f1_improvement_pct[2]:+.1f}%")
print("5. This confirms: Season-Ending = Threshold Issue, Short/Medium = Representation Problem")
print("="*80)