# -*- coding: utf-8 -*-
"""BioBERTv1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WH_bD3Twxtg0NT0MKDgw9U1GT1QUYF4U
"""

!pip install kaggle
!kaggle datasets download -d sananmuzaffarov/european-football-injuries-2020-2025
!unzip european-football-injuries-2020-2025.zip

import pandas as pd
import numpy as np

df = pd.read_csv('full_dataset_thesis - 1.csv')

# Basic Labeling/Exploring
print(f"Total Records: {len(df)}")
print(f"Total Columns: {len(df.columns)}")
print(f"\nColumns: {df.columns.tolist()}")

#print(df.head())
# Check for the injurt description column
print(f"\nSample injury types: ")
print(df['Injury'].head(20))

# Convert dates to datetime
df['injury_start'] = pd.to_datetime(df['injury_from_parsed'])
df['injury_end'] = pd.to_datetime(df['injury_until_parsed'])

# Calculate duration
df['days_missed'] = (df['injury_end'] - df['injury_start']).dt.days

# Remove invalid entries
df = df[df['days_missed'] >= 0] # negative days = error

# Output Data Stats
print(f"\nDays Missed statistics: ")
print(df['days_missed'].describe())

from __future__ import print_function
def classify_severity(days):
  """
  Classify injury severity by days missed
  """
  if days < 7:
    return 'Minor'
  elif days < 21:
    return 'Short-Term'
  elif days < 60:
    return 'Medium-Term'
  elif days < 180:
    return 'Long-Term'
  else:
    return 'Season-Ending'

# Apply Classification
df['severity'] = df['days_missed'].apply(classify_severity)

# Convert to numeric labels for model
severity_mapping = {
    'Minor': 0,
    'Short-Term': 1,
    'Medium-Term': 2,
    'Long-Term': 3,
    'Season-Ending': 4
}
df['severity_'] = df['severity'].map(severity_mapping)

# Check class distribution
print("\nSeverity Distribution:")
print(df['severity'].value_counts())
print("\nClass percentages: ")
print(df['severity'].value_counts(normalize=True) * 100) # Class % Distribution represented w/ decimal

# Assuming the injury column is named 'Injury'
# Adjust based on actual column name in your dataset

# Remove missing values
df = df[df['Injury'].notna()]

# Clean text (optional - BioBERT handles most cases well)
df['injury_text'] = df['Injury'].str.strip()

# Remove any extremely short descriptions (likely errors)
df = df[df['injury_text'].str.len() > 2]

print(f"\nFinal dataset size: {len(df)} records")
print(f"\nSample injury texts:")
for i, text in enumerate(df['injury_text'].head(10)):
    print(f"{i+1}. {text}")

# 1. Reload the data (or use a backup if you made one earlier)
df_full = pd.read_csv('full_dataset_thesis - 1.csv')

# 2. Identify the short ones BEFORE you filter the main dataframe
short_records = df_full[df_full['Injury'].fillna('').str.len() <= 2]
missing_records = df_full[df_full['Injury'].isna()]

# 3. Print them out to inspect
print("--- SHORT DESCRIPTIONS (0-3 chars) ---")
print(short_records['Injury'].unique())

print("\n--- SAMPLE OF DATA THAT WOULD BE REMOVED ---")
print(short_records[['Injury', 'player_name']].head(10))

# Seperate Datast
# TRAIN / TEST / VALIDATION
# 80/10/10
from sklearn.model_selection import train_test_split

# Create feature and label arrays
X = df['injury_text'].values # Text input
y = df['severity_'].values # Numeric labels (0-4)

# First split: 80% train, 20% temp (10%val + 10%test)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.2,      # 20% for val+test
    random_state=42,
    stratify=y    # Maintain class distribution
)

# Second split:
X_val, X_test, y_val, y_test = train_test_split(
     X_temp, y_temp,
    test_size=0.5,      # 50% of 20% for 10% of total
    random_state=42,
    stratify=y_temp     # Maintain class distribution
)


# Verify total percentages
total_samples = len(X)
print(f"Total Samples: {total_samples}")
print(f"Train Samples: {len(X_train)} samples ({len(X_train)/total_samples*100:.1f}%)")
print(f"Validation Samples: {len(X_val)} samples ({len(X_val)/total_samples*100:.1f}%)")
print(f"Test Samples: {len(X_test)} samples ({len(X_test)/total_samples*100:.1f}%)")

# Check class distribution in each split
print("\n" + "-"*60)
print("CLASS DISTRIBUTION ACROSS SPLITS")
print("="*60)

severity_names = ['Minor', 'Short-Term', 'Medium-Term', 'Long-Term', 'Season-Ending']

for split_name, split_labels in [('Training ', y_train), ('Validation ', y_val), ('Test ', y_test)]:
    print(f"\n{split_name} set distribution:")
    unique, counts = np.unique(split_labels, return_counts=True)
    for label, count in zip(unique, counts):
        print(f"{severity_names[label]}: {count} samples ({count/len(split_labels)*100:5.1f}%)")

# TOKENIZE for BioBERT
from transformers import AutoTokenizer

# Load BioBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained('dmis-lab/biobert-v1.1')

# Tokenize all splits
train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    X_val.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding=True,
    max_length=128
)

print("Tokenization complete!")
print(f"Example tokenized injury:")
print(f"Text: {X_train[0]}")
print(f"Token IDs: {train_encodings['input_ids'][0][:20]}...")  # First 20 tokens

# CREATE DATASET CLASS

import torch

class InjuryDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Create datasets
train_dataset = InjuryDataset(train_encodings, y_train)
val_dataset = InjuryDataset(val_encodings, y_val)
test_dataset = InjuryDataset(test_encodings, y_test)

# Load BioBERT Model

from transformers import AutoModelForSequenceClassification

# Load for classification
model = AutoModelForSequenceClassification.from_pretrained(
    'dmis-lab/biobert-v1.1',
    num_labels=5, # 5 severity classes
    problem_type="single_label_classification"
)

# Debug
print(f'Model loaded: {model.__class__.__name__}')
print(f'Number of parameters: {model.num_parameters()}')

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=32,     # Batch size
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="epoch",              # Evaluate on each epoch
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    save_total_limit=2                  # Keep best 2 checkpoints
)

# Evaluation Metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    # Calculate metrics (f1 score)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='weighted'
    )
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

# Train the Model
from transformers import Trainer

# Create trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# Start training
print("Start training...")
trainer.train()

print("\nTraining complete!")

# EVALUATE RESULTS
# Test Set Evaluation

test_results = trainer.evaluate(test_dataset)

print("\n" + "="*50)
print("TEST SET RESULTS")
print("="*50)
for metric, value in test_results.items():
    print(f"{metric}: {value:.4f}")

import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# Get predictions
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(-1)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=severity_names,
    yticklabels=severity_names
    )
plt.title('BioBERT Injurt Severity Classification - Confusion Matrix')
plt.xlabel('Predicted - Severity')
plt.ylabel('Actual - Severity')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300)
plt.show()

# Classification report
print("\n" + "="*50)
print("CLASSIFICATION REPORT")
print("="*50)
print(classification_report(y_test, y_pred, target_names=severity_names))

# ERROR ANALYSIS

# Find misclassified examples
errors = []
for i, (true, pred) in enumerate(zip(y_test, y_pred)):
    if true != pred:
        errors.append({
            'text': X_test[i],
            'true_label': list(severity_mapping.keys())[true],
            'predicted_label': list(severity_mapping.keys())[pred],
            'days_missed': df.iloc[i]['days_missed']
        })
# Show 10 worst errors
print("\n" + "="*50)
print("SAMPLE MISCLASSIFICATIONS")
print("="*50)
for idx, error_data in enumerate(errors[:10]):
    print(f"\n{idx+1}. Injury: {error_data['text']}")
    print(f"   True: {error_data['true_label']} | Predicted: {error_data['predicted_label']}")

# Save the fine-tuned model
model.save_pretrained('./biobert_injury_classifier')
tokenizer.save_pretrained('./biobert_injury_classifier')

print("Model saved to './biobert_injury_classifier'")

# Save results to CSV
results_df = pd.DataFrame({
    'injury_text': X_test,
    'true_label': [list(severity_mapping.keys())[i] for i in y_test],
    'predicted_label': [list(severity_mapping.keys())[i] for i in y_pred]
})
results_df.to_csv('injury_classification_results.csv', index=False)

print("Results saved to 'injury_classification_results.csv'")

# TEST ON NEW INJURIES

def predict_severity(injury_text):
  """
  Predict severity for a new injury description
  """
  # Tokenize
  inputs = tokenizer(
      injury_text,
      return_tensors='pt',
      truncation=True,
      padding=True,
      max_length=128,
  )

  # Get the device of the model
  device = model.parameters().__next__().device

  # Move input tensors to the same device as the model
  inputs = {key: val.to(device) for key, val in inputs.items()}

  # Predict
  model.eval()
  with torch.no_grad():
    outputs = model(**inputs)
    prediction = outputs.logits.argmax(-1).item()

  # Get severity name
  severity_name = list(severity_mapping.keys())[prediction]

  # Get confidence scores
  probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
  # Move probabilities back to CPU for easier printing/handling if needed
  probabilities = probabilities.cpu()

  return severity_name, probabilities

# Test examples
test_injuries = [
    "Hamstring Strain",
    "Anterior Ligament Rupture",
    "Minor Ankle Knock",
    "Fractured Metatarsal"
]

print("\n" + "="*50)
print("PREDICTIONS ON NEW INJURIES")
print("="*50)

for injury in test_injuries:
  severity, confidences = predict_severity(injury)
  print(f"\nInjury: {injury}")
  print(f"Predicted Severity: {severity}")
  print(f"Confidence Scores:")
  for name, prob in zip(severity_names, confidences):
    print(f"{name}: {prob:.2%}")

# ============================================================================
# BIOBERT INJURY CLASSIFICATION - COMPLETE RESULTS ANALYSIS
# ============================================================================
# This script generates all missing visualizations and calculates AUC metrics
# Add this as a new cell in your Colab notebook after training completes
# ============================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
from sklearn.metrics import (
    roc_auc_score,
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score,
    confusion_matrix,
    classification_report
)

# Set professional style for academic papers
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.size'] = 10
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['xtick.labelsize'] = 9
plt.rcParams['ytick.labelsize'] = 9
plt.rcParams['legend.fontsize'] = 9

severity_names = ['Minor', 'Short-Term', 'Medium-Term', 'Long-Term', 'Season-Ending']

print("="*80)
print("BIOBERT COMPLETE RESULTS ANALYSIS")
print("="*80)

# ============================================================================
# STEP 1: CALCULATE MISSING METRICS (AUC Scores)
# ============================================================================

print("\n\n1. CALCULATING AUC METRICS")
print("-"*80)

# Get probability predictions (softmax)
y_probs = predictions.predictions
y_probs_softmax = torch.nn.functional.softmax(torch.tensor(y_probs), dim=-1).numpy()

# Calculate Macro AUC (treats all classes equally)
macro_auc = roc_auc_score(y_test, y_probs_softmax, multi_class='ovr', average='macro')

# Calculate Weighted AUC (weights by class frequency)
weighted_auc = roc_auc_score(y_test, y_probs_softmax, multi_class='ovr', average='weighted')

# Calculate per-class AUC
per_class_auc = roc_auc_score(y_test, y_probs_softmax, multi_class='ovr', average=None)

print(f"Macro AUC (unweighted):    {macro_auc:.4f}")
print(f"Weighted AUC (by support): {weighted_auc:.4f}")
print(f"AUC Gap:                   {macro_auc - weighted_auc:.4f}")
print(f"\nPer-Class AUC Scores:")
for i, name in enumerate(severity_names):
    print(f"  {name:15s}: {per_class_auc[i]:.4f}")

# ============================================================================
# VISUALIZATION 1: BASELINE COMPARISON CHART
# ============================================================================

print("\n\n2. GENERATING VISUALIZATIONS")
print("-"*80)
print("Creating Graph 1: Baseline Comparison...")

fig, ax = plt.subplots(figsize=(10, 6))

# Calculate baselines
random_baseline = 1/5  # 20% for 5 balanced classes
majority_baseline = np.max([np.sum(y_test == i) for i in range(5)]) / len(y_test)
biobert_accuracy = test_results['eval_accuracy']

baselines = ['Random\nGuessing', 'Majority\nClass', 'BioBERT\n(Ours)']
accuracies = [random_baseline, majority_baseline, biobert_accuracy]
colors = ['#d62728', '#ff7f0e', '#2ca02c']

bars = ax.bar(baselines, accuracies, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)

# Add value labels on bars
for bar, acc in zip(bars, accuracies):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{acc:.1%}',
            ha='center', va='bottom', fontweight='bold', fontsize=11)

# Add improvement annotations
improvement_vs_random = (biobert_accuracy - random_baseline) / random_baseline * 100
improvement_vs_majority = (biobert_accuracy - majority_baseline) / majority_baseline * 100

ax.text(2, biobert_accuracy * 0.7,
        f'+{improvement_vs_random:.0f}% vs Random\n+{improvement_vs_majority:.0f}% vs Majority',
        ha='center', fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

ax.set_ylabel('Accuracy', fontweight='bold', fontsize=12)
ax.set_title('BioBERT Performance vs. Baseline Approaches', fontweight='bold', fontsize=14, pad=15)
ax.set_ylim([0, 0.6])
ax.grid(axis='y', alpha=0.3, linestyle='--')

plt.tight_layout()
plt.savefig('graph1_baseline_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph1_baseline_comparison.png")

# ============================================================================
# VISUALIZATION 2: WEIGHTED VS MACRO AUC COMPARISON
# ============================================================================

print("Creating Graph 2: AUC Comparison...")

fig, ax = plt.subplots(figsize=(8, 6))

auc_types = ['Macro AUC\n(Unweighted)', 'Weighted AUC\n(By Frequency)']
auc_scores = [macro_auc, weighted_auc]
colors = ['#1f77b4', '#ff7f0e']

bars = ax.bar(auc_types, auc_scores, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)

for bar, score in zip(bars, auc_scores):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{score:.3f}',
            ha='center', va='bottom', fontweight='bold', fontsize=11)

# Add gap annotation
gap = macro_auc - weighted_auc
ax.annotate('', xy=(0, weighted_auc), xytext=(0, macro_auc),
            arrowprops=dict(arrowstyle='<->', color='red', lw=2))
ax.text(-0.15, (macro_auc + weighted_auc)/2,
        f'Gap: {gap:.3f}',
        fontsize=10, color='red', fontweight='bold',
        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

ax.set_ylabel('AUC Score', fontweight='bold', fontsize=12)
ax.set_title('Macro vs. Weighted AUC-ROC\n(Gap indicates struggle with majority classes)',
             fontweight='bold', fontsize=13, pad=15)
ax.set_ylim([0.5, 0.85])
ax.axhline(y=0.5, color='gray', linestyle='--', alpha=0.5, label='Random Classifier')
ax.grid(axis='y', alpha=0.3, linestyle='--')
ax.legend()

plt.tight_layout()
plt.savefig('graph2_auc_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph2_auc_comparison.png")

# ============================================================================
# VISUALIZATION 3: NORMALIZED CONFUSION MATRIX (CENTRAL TENDENCY BIAS)
# ============================================================================

print("Creating Graph 3: Normalized Confusion Matrix...")

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Left: Absolute counts
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=severity_names,
    yticklabels=severity_names,
    ax=axes[0],
    cbar_kws={'label': 'Count'},
    linewidths=0.5,
    linecolor='gray'
)
axes[0].set_title('Confusion Matrix: Absolute Counts', fontweight='bold', fontsize=13, pad=10)
axes[0].set_ylabel('True Severity', fontweight='bold', fontsize=11)
axes[0].set_xlabel('Predicted Severity', fontweight='bold', fontsize=11)

# Right: Normalized (shows Central Tendency Bias)
sns.heatmap(
    cm_normalized,
    annot=True,
    fmt='.2%',
    cmap='RdYlGn_r',
    xticklabels=severity_names,
    yticklabels=severity_names,
    ax=axes[1],
    cbar_kws={'label': 'Percentage of True Class'},
    linewidths=0.5,
    linecolor='gray',
    vmin=0,
    vmax=0.7
)
axes[1].set_title('Confusion Matrix: Row-Normalized\n(Reveals Central Tendency Bias)',
                  fontweight='bold', fontsize=13, pad=10)
axes[1].set_ylabel('True Severity', fontweight='bold', fontsize=11)
axes[1].set_xlabel('Predicted Severity', fontweight='bold', fontsize=11)

# Highlight Medium-Term column to show central tendency
for ax in axes:
    ax.axvline(x=2, color='red', linewidth=3, alpha=0.3)
    ax.axvline(x=3, color='red', linewidth=3, alpha=0.3)

plt.tight_layout()
plt.savefig('graph3_confusion_matrix_normalized.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph3_confusion_matrix_normalized.png")

# Analyze central tendency
medium_predictions = cm[:, 2].sum()
total_predictions = cm.sum()
print(f"\nCentral Tendency Analysis:")
print(f"  Medium-Term predictions: {medium_predictions} ({medium_predictions/total_predictions*100:.1f}% of all predictions)")
print(f"  This is the model's 'safe bet' under uncertainty")

# ============================================================================
# VISUALIZATION 4: ERROR DISTANCE DISTRIBUTION
# ============================================================================

print("\nCreating Graph 4: Error Distance Distribution...")

# Calculate error distances
error_distances = []
for true, pred in zip(y_test, y_pred):
    error_distances.append(abs(true - pred))

error_distances = np.array(error_distances)

fig, ax = plt.subplots(figsize=(10, 6))

# Count errors by distance
distance_counts = [np.sum(error_distances == i) for i in range(5)]
distance_labels = ['0\n(Correct)', '±1\n(Adjacent)', '±2', '±3', '±4\n(Opposite)']

colors_dist = ['#2ca02c', '#ff7f0e', '#d62728', '#9467bd', '#8c564b']
bars = ax.bar(range(5), distance_counts, color=colors_dist, alpha=0.8, edgecolor='black', linewidth=1.5)

# Add percentages
for i, (bar, count) in enumerate(zip(bars, distance_counts)):
    height = bar.get_height()
    percentage = count / len(error_distances) * 100
    ax.text(bar.get_x() + bar.get_width()/2., height,
            f'{count}\n({percentage:.1f}%)',
            ha='center', va='bottom', fontweight='bold', fontsize=10)

ax.set_xlabel('Prediction Error Magnitude (Classes)', fontweight='bold', fontsize=12)
ax.set_ylabel('Number of Test Samples', fontweight='bold', fontsize=12)
ax.set_title('Distribution of Prediction Errors by Class Distance\n(Supports "Safe Bet" Hypothesis)',
             fontweight='bold', fontsize=13, pad=15)
ax.set_xticks(range(5))
ax.set_xticklabels(distance_labels)
ax.grid(axis='y', alpha=0.3, linestyle='--')

# Add statistics
adjacent_errors = distance_counts[1]
total_errors = sum(distance_counts[1:])
adjacent_pct = adjacent_errors / total_errors * 100 if total_errors > 0 else 0

ax.text(3.5, max(distance_counts) * 0.8,
        f'Adjacent errors: {adjacent_pct:.1f}% of all errors\n'
        f'Model minimizes expected distance',
        fontsize=10, bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7))

plt.tight_layout()
plt.savefig('graph4_error_distance.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph4_error_distance.png")

# ============================================================================
# VISUALIZATION 5: PER-CLASS PERFORMANCE BREAKDOWN
# ============================================================================

print("Creating Graph 5: Per-Class F1 Scores...")

# Get per-class metrics from classification report
report_dict = classification_report(y_test, y_pred, target_names=severity_names, output_dict=True, zero_division=0)

f1_scores = [report_dict[name]['f1-score'] for name in severity_names]
support = [report_dict[name]['support'] for name in severity_names]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: F1 scores with class frequency
x_pos = np.arange(len(severity_names))
colors_f1 = plt.cm.RdYlGn(np.array(f1_scores))

bars = axes[0].barh(severity_names, f1_scores, color=colors_f1, edgecolor='black', linewidth=1.5)

# Add value labels
for i, (bar, score) in enumerate(zip(bars, f1_scores)):
    width = bar.get_width()
    axes[0].text(width + 0.02, bar.get_y() + bar.get_height()/2,
                f'{score:.3f}',
                ha='left', va='center', fontweight='bold', fontsize=10)

axes[0].set_xlabel('F1-Score', fontweight='bold', fontsize=11)
axes[0].set_title('Per-Class F1-Score Performance', fontweight='bold', fontsize=12, pad=10)
axes[0].set_xlim([0, 1])
axes[0].axvline(x=0.5, color='gray', linestyle='--', alpha=0.5, label='Baseline')
axes[0].grid(axis='x', alpha=0.3, linestyle='--')
axes[0].legend()

# Right: Support (sample count) per class
bars2 = axes[1].bar(severity_names, support, color='steelblue', alpha=0.7, edgecolor='black', linewidth=1.5)

for bar in bars2:
    height = bar.get_height()
    axes[1].text(bar.get_x() + bar.get_width()/2., height,
                f'{int(height)}',
                ha='center', va='bottom', fontweight='bold', fontsize=10)

axes[1].set_ylabel('Number of Test Samples', fontweight='bold', fontsize=11)
axes[1].set_title('Class Distribution in Test Set', fontweight='bold', fontsize=12, pad=10)
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(axis='y', alpha=0.3, linestyle='--')

# Add correlation annotation
axes[1].text(0.5, max(support) * 0.85,
            'Note: Season-Ending has\nhigh F1 despite low support',
            transform=axes[1].transData,
            fontsize=9,
            bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.6))

plt.tight_layout()
plt.savefig('graph5_per_class_performance.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph5_per_class_performance.png")

# ============================================================================
# VISUALIZATION 6: ROC CURVES (PER CLASS)
# ============================================================================

print("Creating Graph 6: ROC Curves...")

fig, ax = plt.subplots(figsize=(10, 8))

# Plot ROC curve for each class
colors_roc = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

for i, (name, color) in enumerate(zip(severity_names, colors_roc)):
    # Create binary labels (one-vs-rest)
    y_binary = (y_test == i).astype(int)
    y_score = y_probs_softmax[:, i]

    # Calculate ROC curve
    fpr, tpr, _ = roc_curve(y_binary, y_score)
    roc_auc = auc(fpr, tpr)

    # Special styling for Season-Ending
    if name == 'Season-Ending':
        ax.plot(fpr, tpr, color=color, lw=3,
                label=f'{name} (AUC = {roc_auc:.3f}) ★',
                linestyle='--')
    else:
        ax.plot(fpr, tpr, color=color, lw=2,
                label=f'{name} (AUC = {roc_auc:.3f})')

# Diagonal reference line
ax.plot([0, 1], [0, 1], 'k--', lw=2, alpha=0.3, label='Random Classifier')

ax.set_xlabel('False Positive Rate', fontweight='bold', fontsize=12)
ax.set_ylabel('True Positive Rate', fontweight='bold', fontsize=12)
ax.set_title('Per-Class ROC Curves\n(Season-Ending shows high AUC despite low default F1)',
             fontweight='bold', fontsize=13, pad=15)
ax.legend(loc='lower right', fontsize=10)
ax.grid(alpha=0.3, linestyle='--')
ax.set_xlim([0, 1])
ax.set_ylim([0, 1])

plt.tight_layout()
plt.savefig('graph6_roc_curves.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph6_roc_curves.png")

# ============================================================================
# VISUALIZATION 7: PRECISION-RECALL CURVES
# ============================================================================

print("Creating Graph 7: Precision-Recall Curves...")

fig, ax = plt.subplots(figsize=(10, 8))

for i, (name, color) in enumerate(zip(severity_names, colors_roc)):
    y_binary = (y_test == i).astype(int)
    y_score = y_probs_softmax[:, i]

    precision, recall, _ = precision_recall_curve(y_binary, y_score)
    avg_precision = average_precision_score(y_binary, y_score)

    if name == 'Season-Ending':
        ax.plot(recall, precision, color=color, lw=3,
                label=f'{name} (AP = {avg_precision:.3f}) ★',
                linestyle='--')
    else:
        ax.plot(recall, precision, color=color, lw=2,
                label=f'{name} (AP = {avg_precision:.3f})')

ax.set_xlabel('Recall', fontweight='bold', fontsize=12)
ax.set_ylabel('Precision', fontweight='bold', fontsize=12)
ax.set_title('Per-Class Precision-Recall Curves\n(Shows threshold tuning potential)',
             fontweight='bold', fontsize=13, pad=15)
ax.legend(loc='best', fontsize=10)
ax.grid(alpha=0.3, linestyle='--')
ax.set_xlim([0, 1])
ax.set_ylim([0, 1])

# Add annotation
ax.text(0.6, 0.2,
        'Season-Ending curve shows\nthreshold tuning potential',
        fontsize=10,
        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.6))

plt.tight_layout()
plt.savefig('graph7_precision_recall_curves.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph7_precision_recall_curves.png")

# ============================================================================
# VISUALIZATION 8: CONFIDENCE DISTRIBUTION
# ============================================================================

print("Creating Graph 8: Confidence Distribution...")

# Get max probability for each prediction (model confidence)
confidences = np.max(y_probs_softmax, axis=1)
correct = (y_test == y_pred)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: Histogram comparison
axes[0].hist(confidences[correct], bins=30, alpha=0.7, label='Correct Predictions',
             color='green', edgecolor='black')
axes[0].hist(confidences[~correct], bins=30, alpha=0.7, label='Incorrect Predictions',
             color='red', edgecolor='black')
axes[0].set_xlabel('Model Confidence (Max Probability)', fontweight='bold', fontsize=11)
axes[0].set_ylabel('Frequency', fontweight='bold', fontsize=11)
axes[0].set_title('Confidence Distribution by Correctness', fontweight='bold', fontsize=12, pad=10)
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3, linestyle='--')

# Add mean lines
mean_correct = np.mean(confidences[correct])
mean_incorrect = np.mean(confidences[~correct])
axes[0].axvline(mean_correct, color='green', linestyle='--', linewidth=2,
                label=f'Mean Correct: {mean_correct:.3f}')
axes[0].axvline(mean_incorrect, color='red', linestyle='--', linewidth=2,
                label=f'Mean Incorrect: {mean_incorrect:.3f}')
axes[0].legend()

# Right: Box plot
data_to_plot = [confidences[correct], confidences[~correct]]
bp = axes[1].boxplot(data_to_plot, labels=['Correct', 'Incorrect'],
                     patch_artist=True, widths=0.6)
bp['boxes'][0].set_facecolor('lightgreen')
bp['boxes'][1].set_facecolor('lightcoral')

axes[1].set_ylabel('Model Confidence', fontweight='bold', fontsize=11)
axes[1].set_title('Confidence Distribution Comparison', fontweight='bold', fontsize=12, pad=10)
axes[1].grid(axis='y', alpha=0.3, linestyle='--')

# Add mean values as text
for i, (mean_val, label) in enumerate([(mean_correct, 'Correct'), (mean_incorrect, 'Incorrect')], 1):
    axes[1].text(i, mean_val, f'μ={mean_val:.3f}',
                ha='center', va='bottom', fontweight='bold', fontsize=9)

plt.tight_layout()
plt.savefig('graph8_confidence_distribution.png', dpi=300, bbox_inches='tight')
plt.show()
print("✓ Saved: graph8_confidence_distribution.png")

# Calculate calibration insight
calibration_gap = mean_correct - mean_incorrect
print(f"\nCalibration Analysis:")
print(f"  Mean confidence (correct):   {mean_correct:.3f}")
print(f"  Mean confidence (incorrect): {mean_incorrect:.3f}")
print(f"  Calibration gap:             {calibration_gap:.3f}")
if calibration_gap > 0.1:
    print(f"  ✓ Model shows good calibration (knows when it's uncertain)")
else:
    print(f"  ⚠ Model shows poor calibration (overconfident on errors)")

# ============================================================================
# SUMMARY STATISTICS TABLE
# ============================================================================

print("\n\n3. GENERATING SUMMARY TABLES")
print("-"*80)

# Create comprehensive summary
summary_data = {
    'Metric': [
        'Overall Accuracy',
        'Macro F1-Score',
        'Weighted F1-Score',
        'Macro AUC',
        'Weighted AUC',
        'AUC Gap',
        'Mean Confidence (Correct)',
        'Mean Confidence (Incorrect)',
        'Adjacent Error Rate',
        'Central Tendency (Medium predictions)'
    ],
    'Value': [
        f"{test_results['eval_accuracy']:.4f}",
        f"{test_results['eval_f1']:.4f}",
        f"{test_results['eval_f1']:.4f}",
        f"{macro_auc:.4f}",
        f"{weighted_auc:.4f}",
        f"{macro_auc - weighted_auc:.4f}",
        f"{mean_correct:.4f}",
        f"{mean_incorrect:.4f}",
        f"{adjacent_pct:.1f}%",
        f"{medium_predictions/total_predictions*100:.1f}%"
    ]
}

summary_df = pd.DataFrame(summary_data)
print("\nOverall Performance Summary:")
print(summary_df.to_string(index=False))

# Save to CSV
summary_df.to_csv('biobert_summary_metrics.csv', index=False)
print("\n✓ Saved: biobert_summary_metrics.csv")

# ============================================================================
# PER-CLASS DETAILED TABLE
# ============================================================================

per_class_data = {
    'Class': severity_names,
    'Precision': [report_dict[name]['precision'] for name in severity_names],
    'Recall': [report_dict[name]['recall'] for name in severity_names],
    'F1-Score': [report_dict[name]['f1-score'] for name in severity_names],
    'AUC': per_class_auc,
    'Support': [int(report_dict[name]['support']) for name in severity_names]
}

per_class_df = pd.DataFrame(per_class_data)
print("\n\nPer-Class Performance Table:")
print(per_class_df.to_string(index=False))

per_class_df.to_csv('biobert_per_class_metrics.csv', index=False)
print("\n✓ Saved: biobert_per_class_metrics.csv")

# ============================================================================
# FINAL SUMMARY
# ============================================================================

print("\n\n" + "="*80)
print("ANALYSIS COMPLETE - ALL VISUALIZATIONS GENERATED")
print("="*80)

print("\n📊 Generated Visualizations:")
print("  1. graph1_baseline_comparison.png")
print("  2. graph2_auc_comparison.png")
print("  3. graph3_confusion_matrix_normalized.png")
print("  4. graph4_error_distance.png")
print("  5. graph5_per_class_performance.png")
print("  6. graph6_roc_curves.png")
print("  7. graph7_precision_recall_curves.png")
print("  8. graph8_confidence_distribution.png")

print("\n📈 Generated Data Files:")
print("  1. biobert_summary_metrics.csv")
print("  2. biobert_per_class_metrics.csv")

print("\n✅ All files are publication-ready at 300 DPI")
print("✅ Use these visualizations for your April 11 submission")

print("\n" + "="*80)
print("KEY FINDINGS SUMMARY:")
print("="*80)
print(f"1. Model beats baselines by {improvement_vs_random:.0f}% (vs random) and {improvement_vs_majority:.0f}% (vs majority)")
print(f"2. AUC gap of {macro_auc - weighted_auc:.3f} confirms struggle with majority classes")
print(f"3. {adjacent_pct:.1f}% of errors are adjacent-class (supports 'safe bet' hypothesis)")
print(f"4. Medium-Term receives {medium_predictions/total_predictions*100:.1f}% of predictions (central tendency bias)")
print(f"5. Season-Ending: High AUC ({per_class_auc[4]:.3f}) but low default F1 ({f1_scores[4]:.3f}) = threshold issue")
print(f"6. Short/Medium: Similar low AUC ({per_class_auc[1]:.3f}/{per_class_auc[2]:.3f}) = representation problem")
print("="*80)