# -*- coding: utf-8 -*-
"""CHIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBSNBlVKcoaO0T0Ssjz-_KqJA9t3rq64
"""

#Description: This program is a custom simulation of a coding techinal interview

#Import the libraries
import re
import random

#Create a list of pre-defined responses similar to Eliza's by usin a dictionary aka a key value pair
# Reflections for grammar

TRANSITIONS = [
    "Great, moving on;",
    "Based on what you've said,",
    "I see. Let's dig a bit deeper, ",
    "Interesting response;",
    "Got it. Next question,",
]

REFLECTIONS = {
    "i am": "you are",
    "i": "you",
    "you're": "I am",
    "me": "you",
    "mine": "your",
    "am": "are",
    "yours": "mine",
    "a person is": "they are",
    "are": "am",
    "fixing": "refactoring",
    "my group": "your role in the group",
    "my code": "Your implementation",
    "problem": "technical hurdle",
    "challenge": "technical hurdle",
    "doing": "implementing"
}

TECHNICAL_SCRIPTS = {
    "java": {
        r".*\b([Ss]trings?)\b.*": ["Are strings mutable in Java?", "How does the JVM handle memory when you repeatedly modify a String in a loop?"],

        r".*\b([Dd]oubles?|[Ff]loats?)\b.*": ["Explain in any given case why would you generally choose a Double as opposed to a Float as a data type"],

        r".*\b([Ii]nt(eger|egers)?|[Dd]ivide|[Dd]ivision)\b.*": ["Lets just say I wanted to solve for the full numerical value of 9 divided by 4, explain the result of representing that value as an Int, and what other methods might work better?"],

        r".*\b([Qq]ueues?|[Ss]tacks?)\b.*": ["What Data Structure would you implement for a fast food drive through line where we want to minimize the time a customer waits?"],

        r".*\b([Ll]ifo|[Ff]ilo|[Ss]tacks?)\b.*": ["What does the acronym LIFO or FILO mean to you based on your knowledge of DS and Java?"],

        r".*\b([Cc]ollect(s|ing|ed|ions?)|[Ss]ets?)\b.*": ["What is the key difference between a collection and a set?"],

        r".*\b([Ll]oop(s|ing|ed)|[Ii]teration(s|ing|ed))\b.*": ["How many iterations does this loop go through for (int i = 1; i < 10; i++)?"],

        r".*\b([Cc]ast(s|ing|ed)?|[Ii]nt(eger|egers)?)\b.*": ["Can you cast String '123' into int 123 in Java?"],

        r".*\b([Ii]nherit(ance|ed|s|ing)?|[Ee]ncapsulat(e|es|ing|ion|ed)?)\b.*": ["Explain what 'extends' keyword is used for."],

        r".*\b([Cc]lass(es)?|[Oo]bjects?)\b.*": ["Explain what the 'extends' keyword is used for.", "Explain the hierarchy of Java Exception classes."],

        r".*\b([Mm]ethods?|[Ff]unctions?)\b.*": ["Explain what the 'extends' keyword is used for."],

        r".*\b([Pp]rocess(es|ing|ed)?|[Tt]asks?|[Ii]nstances?)\b.*": ["How does Java handle multithreading?"],

        r".*\b([Ee]xceptions?|[Cc]ompile(s|ing|d)?|[Dd]ebug(s|ging)?)\b.*": ["What is the difference between Checked Exception and Unchecked Exception?", "How does Java execute code compared to Python?"],

        r".*\b([Jj]oin(s|ing|ed)?|[Cc]oncatenates?)\b.*": ["In Java, what is the difference between using the + operator to concatenate strings in a loop versus using a StringBuilder?", "When it is acceptable to use + versus using StringBuilder?"],

        r".*\b([Rr]ecurs(ions?|ive|e|ively)?|[Ii]ter(ations?|ative))\b.*": ["How does recursion differ from iteration?", "What is the base case in recursion and why is it important?", "Can you provide an example of a problem that can be solved using recursion?"],

        r".*\b([Ss]ort(ed|ings?)?|[Aa]lgorithm(s|ic|ically))\b.*": ["Which sort algorithm works best on mostly sorted data?", "What is a searching algorithm?", "Why Sorting algorithms are important?"],

        r".*\b(([Ee]n|[Dd]e)?[Cc]rypt(ed|s|ing)?|[Ss]ecur(e|ity|ed)?)\b.*": ["What is a VPN?", "Define encryption and decryption?", "What is the difference between hashing and encryption?"],

        r".*\b([Mm]emor(ize|y)?|[Ss]pac(ed|es|ing|[Ss]tor(age|e|ing)?))\b.*": ["What is the difference between storage and memory in a computer?, Differentiate between Physical memory and Virtual Memory."]
    },
    "python": {
        r".*\b([Ss]trings?)\b.*": [ "Are strings mutable in Python?", "What happens in Python memory-wise when you repeatedly modify a string inside a loop?", "Show the two notations in Python that strings can be created using."],

        r".*\b([Dd]oubles?|[Ff]loats?)\b.*": ["Explain why Python uses float by default for decimal numbers and how it differs from higher-precision numeric types like Decimal.", "Python doesn't have a 'Double' type like Java. How does Python handle high-precision floating-point arithmetic differently than an Integer?"],

        r".*\b([Ii]nt(eger|egers)?|[Dd]ivide|[Dd]ivision)\b.*": ["If you compute 9 divided by 4 in Python, what result do you get, and how does this differ from integer division?"],

        r".*\b([Qq]ueues?|[Ss]tacks?)\b.*": ["Which Python data structure would you use to model a fast food drive-through line where customers are served in order?"],

        r".*\b([Ll]ifo|[Ff]ilo|[Ss]tacks?)\b.*": ["What does the acronym LIFO or FILO mean, and how is this behavior represented in Python data structures?"],

        r".*\b([Cc]ollect(s|ing|ed|ions?)|[Ss]ets?)\b.*": ["What is the key difference between a list and a set in Python?"],

        r".*\b([Ll]oop(s|ing|ed)|[Ii]teration(s|ing|ed))\b.*": ["How many iterations does this loop execute in Python: for i in range(1, 10)?"],

        r".*\b([Cc]ast(s|ing|ed)?|[Ii]nt(eger|egers)?)\b.*": ["Can you convert the string '123' into the integer 123 in Python, and how would you do it?"],

        r".*\b([Ii]nherit(ance|ed|s|ing)?|[Ee]ncapsulat(e|es|ing|ion|ed)?)\b.*": ["Explain how inheritance works in Python and how a subclass extends a parent class."],

        r".*\b([Cc]lass(es)?|[Oo]bjects?)\b.*": ["Explain how classes and objects work in Python.", "How does Python handle exceptions using class hierarchy?"],

        r".*\b([Mm]ethods?|[Ff]unctions?)\b.*": ["What is the difference between a function and a method in Python?"],

        r".*\b([Pp]rocess(es|ing|ed)?|[Tt]asks?|[Ii]nstances?)\b.*": ["How does Python handle concurrency using threading and multiprocessing?"],

        r".*\b([Ee]xceptions?|[Cc]ompile(s|ing|d)?|[Dd]ebug(s|ging)?)\b.*": ["What is the difference between runtime errors and syntax errors in Python?","How does Python execute code compared to a compiled language?"],

        r".*\b([Jj]oin(s|ing|ed)?|[Cc]oncatenates?)\b.*": ["In Python, what is the difference between concatenating strings with + in a loop versus using str.join()?","When is it appropriate to use + versus join() for strings in Python?","If you need to concatenate 10,000 strings, why is using .join() significantly more efficient than using the + operator?"],

        r".*\b([Ss]pace(d|s|ing)?|[Ii]ndent(ation)?)\b.*": ["How is spacing and indentation applied differently in Python compared to Java?"],

        r".*\b([Rr]ecurs(ions?|ive|e|ively)?|[Ii]ter(ations?|ative))\b.*": ["How does recursion differ from iteration in Python?","What is a base case in Python recursion and why is it important?","Can you give an example of a problem well-suited for recursion in Python?"],

        r".*\b([Ss]ort(ed|ings?)?|[Aa]lgorithm(s|ic|ically))\b.*": ["Which sorting algorithm performs best on mostly sorted data?","What is a searching algorithm in Python?","Why are sorting algorithms important in programming?"],

        r".*\b(([Ee]n|[Dd]e)?[Cc]rypt(ed|s|ing)?|[Ss]ecur(e|ity|ed)?)\b.*": ["What is a VPN?","Define encryption and decryption.","What is the difference between hashing and encryption?"],

        r".*\b([Mm]emor(ize|y)?|[Ss]pac(ed|es|ing|[Ss]tor(age|e|ing)?))\b.*": ["What is the difference between storage and memory in a computer?", "Differentiate between physical memory and virtual memory."]
    },
    "general": {
        r".*\b([Pp]rojects?)\b.*": ["Could you tell me about a challenge you faced during that or another project and how you resolved it?"]
    }
}

def reflect(text: str) -> str: # Replace phrases using REFLECTIONS, longest-first, with word boundaries where possible.

    s = text.lower()

    # Sort keys longest->shortest so "my code" is replaced before "my"
    keys = sorted(REFLECTIONS.keys(), key=len, reverse=True)

    for k in keys: # for each key in keys
        v = REFLECTIONS[k] # value is the reflection of Key

        # If key contains letters/numbers, use word boundaries; otherwise replace
        if re.search(r"[A-Za-z0-9']", k):
            pattern = r"\b" + re.escape(k) + r"\b"
            s = re.sub(pattern, v, s)
        else:
            s = s.replace(k, v)

    return s

EXIT_WORDS = {"exit", "quit", "bye", "goodbye"}

def chip_chat():
    #INTRODUCTION
    print("CHIP: Hello! You can call me Sr. Professor Dev CHIP!")
    print("CHIP: I’m here for a practice technical interview.")
    input("CHIP: Press Enter when you're ready...\nYou: ")

    name = input("CHIP: Let's start with your first name.\nYou: ").strip() or "there"

    print(f"CHIP: On a scale of 1–10, how would you rate your Git or Socket Programming skills, {name}?")
    rating_raw = input("You: ")
    match = re.search(r"\b([1-9]|10)\b", rating_raw)
    comfort = int(match.group()) if match else 5

    # Comfort Logic
    if comfort >= 8:
        opener = "Excellent."
    elif comfort >= 5:
        opener = "Great."
    elif comfort >= 3:
        opener = "Not bad."
    else:
        opener = "No worries."

    # language selection
    language = None
    while language is None:
        lang_raw = input(f"CHIP: {opener} Choose a language to focus on (Java / Python).\nYou: ").lower()
        m = re.search(r"\b(java|python)\b", lang_raw)
        if m: # if found language
            language = m.group(1) # set "language" to that value
        else:
            print("CHIP: I only support Java or Python right now.\n")

    print(f"CHIP: Awesome. We'll do {language.capitalize()}.")
    print(f"CHIP: Now, {name}—tell me briefly about your previous software development experience.")

    current_options = {**TECHNICAL_SCRIPTS[language], **TECHNICAL_SCRIPTS["general"]} # Access each index into TECHNICAL_SCRIPTS (Uses dictionary unpacking (**) to merge them into one dictionary)

    while True:
        user_input_raw = input("You: ").strip()

        if not user_input_raw:
            print("CHIP: Give me a sentence or two—anything to start with.")
            continue

        if any(w in user_input_raw.lower() for w in EXIT_WORDS):
            print("CHIP: Thank you for your time. My assistant will see you out now.")
            break

        # Build one response per user message
        response = None

        #  Try pattern matches first
        for pattern, responses in current_options.items():
            if re.search(pattern, user_input_raw, re.IGNORECASE):
                response = random.choice(responses)
                break

        #  If nothing matched, it chooses fallback (Eliza reflection or random technical)
        # If no pattern matched: Reflects the user's input using the reflect() function
        # 50% chance: Uses the reflection in a therapeutic-style question
        # 50% chance: Picks a random technical question with a transition phrase
        if response is None:
            reflected = reflect(user_input_raw)

            # Pick one fallback style
            if random.random() < 0.50:
                response = f'When you say "{reflected}", what part mattered most to you?' #Reflection
            else:
                pool = []
                for q_list in TECHNICAL_SCRIPTS[language].values():
                    pool.extend(q_list)

                transition = random.choice(TRANSITIONS)
                question = random.choice(pool)
                response = f"{transition} {question}" # Technical Response

        print(f"CHIP: {response}")

if __name__ == "__main__":
    chip_chat()